Add GitHub Actions workflow
pmem/benchmarking pull request #2
Opened 2021-01-21 16:09 UTC by zemdom

Workflow for scanning license headers and static analysis of Ansible playbooks.

2021-05-20 08:47 UTC, mmatuszek1 commented on utils/check_license/check-headers.sh
> +# Copyright 2016-2020, Intel Corporation
Copyright 2021

2021-05-20 08:48 UTC, mmatuszek1 commented on utils/check_license/file-exceptions.sh
> +# Copyright 2016-2019, Intel Corporation
Copyright 2021

2021-05-21 10:47 UTC, mmatuszek1 approved these changes

2021-05-24 13:55 UTC, hsoltysi requested changes
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/benchmarking/2)* status: all files reviewed, 2 unresolved discussions (waiting on @mmatuszek1 and @zemdom)

___
*[utils/check_license/check-headers.sh, line 3 at r1](https://reviewable.io/reviews/pmem/benchmarking/2#-MaTMXQlQjXV8sp08Iod-r1-3:-MaTW8DB5SnKi9oED6xI:b-j9huyq) ([raw file](https://github.com/pmem/benchmarking/blob/866df194aab23631a33727155cbfe7d5061e7519/utils/check_license/check-headers.sh#L3)):*
<details><summary><i>Previously, mmatuszek1 wrote…</i></summary><blockquote>

Copyright 2021
</blockquote></details>

It seems we should stay with original file dates, when not altering file. We'd prefer to get newer version of this checker from:
 https://github.com/pmem/pmemkv/blob/master/utils/check_license/check-headers.sh


<!-- Sent from Reviewable.io -->

2021-07-23 16:35 UTC, hsoltysi approved these changes
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/benchmarking/2)* status: all files reviewed, 2 unresolved discussions (waiting on @mmatuszek1 and @zemdom)



<!-- Sent from Reviewable.io -->

2021-07-23 16:35 UTC, hsoltysi approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/benchmarking/2)* status: all files reviewed, 2 unresolved discussions (waiting on @mmatuszek1 and @zemdom)



<!-- Sent from Reviewable.io -->

2021-07-23 16:36 UTC, merged